export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.png",
      username: "Durgesh Mahajan",
    },
    {
      id:2,
      profilePicture: "assets/person/2.png",
      username: "Rutuja Patil",
    },
    {
      id:3,
      profilePicture: "assets/person/3.png",
      username: "Vaishnavi Mokadam",
    },
    {
      id:4,
      profilePicture: "assets/person/4.png",
      username: "Nishant Bhosale  ",
    },
    {
      id:5,
      profilePicture: "assets/person/5.png",
      username: "Rajat Nawale",
    },
    {
      id:6,
      profilePicture: "assets/person/6.png",
      username: "Kiran Gaikwad",
    },
    {
      id:7,
      profilePicture: "assets/person/7.png",
      username: "Aayush Kakade",
    },
    {
      id:8,
      profilePicture: "assets/person/8.png",
      username: "Suraj Savji",
    },
    {
      id:9,
      profilePicture: "assets/person/9.png",
      username: "Viraj Gore",
    },
    {
      id:10,
      profilePicture: "assets/person/10.png",
      username: "Omi Gaikwad",
    },
    {
      id:11,
      profilePicture: "assets/person/11.png",
      username: "Anjali Kumari",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Night captures 📷😉",
      photo: "assets/post/1.png",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/2.png",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Clouds and raindrops! 🌧🍃",
      photo: "assets/post/3.png",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc: "A Day to be Remembered!!💫",
      photo: "assets/post/5.png",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Crazy Crazy show !",
      photo: "assets/post/7.png",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "___The best thing about India is monsoon___",
      photo: "assets/post/9.png",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc:"❄️White lips, Cold hands, pale face, warm heart breathing in snowflakes🌨 Feeling frosty ☃️",
      photo: "assets/post/10.png",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];